name = "gravity-well-arena-leaderboard"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"

[build]
command = "cargo install worker-build && worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "gravity-leaderboard"
database_id = "dfeef3b3-f948-478f-bc96-a559e402869f"
migrations_dir = "migrations"
